name: tundra
version: '0.1.0'
summary: MyAnimeList scrobbler
description: |
  Tundra is a simple automatic scrobbler for
  MyAnimeList. It detects running video players,
  checks for any anime currently playing, and
  automatically marks them as watched on your
  account.
  Make sure your player supports MPRIS before
  using Tundra.
license: GPL-3.0
icon: snap/gui/tundra.svg

base: core18
grade: stable
confinement: strict

parts:
  tundra:
    plugin: rust
    source: .
    build-packages:
      - pkg-config
      - libssl-dev

apps:
  tundra:
    command: bin/tundra
    extensions: [gnome-3-28]
    slots:
      - dbus-daemon
    plugs:
      - network
      - mpris
    common-id: com.m4tx.Tundra

slots:
  dbus-daemon:
    interface: dbus
    bus: session
    name: com.m4tx.Tundra
